- name: Install and start Apache Playbook
  hosts: server1
  tasks:
    - name: Install and start Apache
      block:
        - name: Update Cache
          apt:
           update_cache: yes
           force_apt_get: yes  
        - name: Install apache
          apt:
            name: apache2
            update_cache: yes
            state: latest
        - name: Start and enable Apache
          service:
            name: apache2
            state: started
            enabled: yes
    - name: This task is outside the block
      debug:
        msg: "I am outside the block"
