---
- name: First folder
  hosts: all
  tasks:
    - name: create developers group
      group: 
        name: developers
    - name: create security group
      group: 
        name: security
    - name: create finance group 
      group:
        name: finance
...
